### ISSUE TITLE
Filter doesnt show right results

### ISSUE THREAD

**Issue by mahish** [mahish/Mapy-usmrceni#18]
After we added the info box functionality, the period filter doesnt show relevant output.

**Comment by sevcikra** [comment]
I think the problem is in the UI itself:
`<input type=range class="range" min=1948 max=1951 value=1 id=obdobi step=1 list=zvolitObdobi oninput="draw(map, mapsDataJSON, value)">`

Basically it send a nonsense parameters to filter the data, Do I guess the solution is to fix the UI.
JS expects the value in form _from,to_ sent via the draw function.

RS

**Comment by mahish** [comment]
The problem was solved by switching back to radio buttons from range slider. As discussed in #17 .
